# Generated by Django 6.0 on 2025-12-17 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. Spacious 1 Bedroom near Mazeras High School', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location_area', models.CharField(default='Mazeras Central', max_length=100)),
                ('google_maps_link', models.CharField(blank=True, help_text='Paste Google Maps pin link here', max_length=500)),
                ('distance_to_highway', models.DecimalField(blank=True, decimal_places=1, help_text='Distance in KM', max_digits=4, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_phone', models.CharField(default='0700000000', help_text='e.g. 0712345678 (For WhatsApp)', max_length=15)),
                ('property_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('BEDSITTER', 'Bedsitter'), ('1BED', 'One Bedroom'), ('2BED', 'Two Bedroom'), ('3BED', 'Three Bedroom +'), ('SHOP', 'Commercial/Shop')], default='SINGLE', max_length=20)),
                ('water_source', models.CharField(choices=[('MAWASCO', 'Council Water (Mawasco)'), ('BOREHOLE', 'Salty/Borehole'), ('FRESH_TANK', 'Fresh Water Tank'), ('NONE', 'No Water Connection')], default='MAWASCO', max_length=20)),
                ('has_token_electricity', models.BooleanField(default=True, verbose_name='KPLC Token')),
                ('is_tiled', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Checked by Makazi Link Team?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/%Y/%m/')),
                ('is_feature', models.BooleanField(default=False, help_text='Is this the main photo?')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
