# Generated by Django 6.0 on 2025-12-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(default='0700000000', help_text='e.g. 0712345678 (For WhatsApp)', max_length=15),
        ),
    ]
