# Generated by Django 6.0 on 2025-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(default='0712345678', help_text='Contact number for this property', max_length=20),
        ),
    ]
