# Generated by Django 6.0 on 2025-12-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(default='0712345678', help_text='Landlord phone number for inquiries', max_length=20),
        ),
    ]
